### ISSUE TITLE
Error executing query on foreign table when foreign server uses FDW based on JDBC connection

### ISSUE THREAD

**Issue by jtsalten** [bdeboe/isc-datafest#3] opened 2023-10-18 15:30 UTC
**IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2023.3 (Build 233U) Tue Sep 19 2023 15:25:13 EDT**

Here is the sequence:
-----
[SQL]USER>>CREATE FOREIGN SERVER datafest.MySelf FOREIGN DATA WRAPPER JDBC CONNECTION 'MySelf'
17.     CREATE FOREIGN SERVER datafest.MySelf FOREIGN DATA WRAPPER JDBC CONNECTION 'MySelf'
1 Row Affected
statement prepare time(s)/globals/cmds/disk: 0.0068s/2,172/17,436/0ms
          execute time(s)/globals/cmds/disk: 0.0137s/9,880/146,107/0ms
                                query class: %sqlcq.USER.cls16
---------------------------------------------------------------------------
[SQL]USER>>CREATE FOREIGN TABLE datafest.RemoteDelhi SERVER datafest.MySelf TABLE 'datafest.Delhi'
18.     CREATE FOREIGN TABLE datafest.RemoteDelhi SERVER datafest.MySelf TABLE 'datafest.Delhi'
0 Rows Affected
statement prepare time(s)/globals/cmds/disk: 0.0073s/2,172/19,567/0ms
          execute time(s)/globals/cmds/disk: 0.1416s/56,801/481,826/0ms
                                query class: %sqlcq.USER.cls15
---------------------------------------------------------------------------
[SQL]USER>>select * from datafest.RemoteDelhi
19.     select * from datafest.RemoteDelhi
OBSDATE HUMIDITY        PRESSURE        TEMPERATURECEL  WINDSPEED 
[SQLCODE: <-230>:<Foreign table query Execute() failed>]
[%msg: <Foreign Tables - ERROR #8104: Gateway Exception: <GATEWAY> com.intersystems.gateway.GatewayException com.intersystems.gateway.JavaGateway.dynamicExecuteMethod(JavaGateway.java:3748) Remote database reported error: Method not found: com.intersystems.xdbc.gateway.ForeignConnection.prepareStatement(3)>]
0 Rows(s) Affected
statement prepare time(s)/globals/cmds/disk: 0.0515s/44,400/231,301/0ms
          execute time(s)/globals/cmds/disk: 0.0177s/114/4,764/0ms
                                query class: %sqlcq.USER.cls16
--------------------------------------------------------------------------

**Comment by bdeboe** [comment] 2023-10-18 18:31
When I try these commands with the default 2023.2-based image, I get an error earlier on, because of the synthetic row ID column in foreign table isn't private and you can't "add" it when creating a foreign table of a foreign table:
```
 CREATE FOREIGN TABLE datafest.RemoteDelhi SERVER datafest.MySelf TABLE 'datafest.Delhi'

[SQLCODE: <-306>:<Column with this name already exists>]
[%msg: <Column of name '%FTID' already exists>]
```
This is expected and is addressed in 2023.3 (by making that system column private).
Creating a foreign table based on a regular table works fine on 2023.2.

I can reproduce the issue on the 2023.3 preview and will log internally.

**Comment by bdeboe** [comment] 2023-10-18 18:47
After checking with the developer, this issue was already caught internally and has been fixed last month, but the fix involved both server and jarfile changes so it took a while to trickle through. It should be part of the 2023.3.0.239 kit we'll publish as the next developer preview this week. Talking about timing!

**Comment by bdeboe** [comment] 2023-10-22 10:03
The latest 2023.3 preview (build 239, published Oct 20) includes the fix for this issue. If you rebuild the image, the script should pick up that base image and you should no longer see this issue

**Closed as completed by bdeboe** 2023-10-22 10:03 UTC
Labels: bug
